"""The governance kit: fleets, the aggregator's view, selection, abstention, and shape.

Findings 18 through 29 are measurements over a small set of shared objects -- a fleet of
simulated analysts, the aggregate a server actually holds, a selection rule, a decision to
withhold, and a statistic over vote dispersion. Those objects were defined inside the
measurement scripts and imported between them: thirty-four names crossed script
boundaries, two scripts were each imported by seven others, and one import reached past a
leading underscore. The scripts had become a library without becoming importable.

This package is that library. The scripts keep what is genuinely theirs -- grids, budgets,
ladders, artifact schemas, and the exit-code protocol a sweep matches on -- and a test
asserts that no script imports another.

The re-exports below are the supported surface. Import from the submodules for anything
else, and expect the submodule layout to be the stable thing rather than this list.
"""

from pharos.governance.abstention import (
    HALVED,
    REPORT_BUDGET,
    AbstentionCell,
    beats_every_draw,
    first_budget_halving,
    score,
)
from pharos.governance.audit import (
    REPAIRED,
    AuditOutcome,
    Scored,
    ThresholdSpread,
    authority_ruling,
    baseline_errors,
    evaluate_audit,
    summarize_thresholds,
    threshold,
)
from pharos.governance.channel import (
    PERMUTATION_SEED,
    PERMUTATIONS,
    ChannelCarriage,
    Detection,
    compartment_carriage,
    detect,
    rates_from,
    scan_channels,
    stratified_delta,
    verdict_rates,
)
from pharos.governance.fleet import (
    BLIND,
    BLIND_RUNGS,
    CHANNEL_ENTANGLEMENT_SLACK,
    LATENT_ATTEMPTS,
    LATENT_CARRIAGE_QUANTILE,
    LATENT_NULL_DRAWS,
    LATENT_SEED_STRIDE,
    LATENT_SLICE,
    MASK_SEED,
    REFUSED_EXIT,
    RUNGS,
    WRONG_THRESHOLD,
    ChannelCheck,
    ChannelUnusableError,
    LatentSlice,
    assert_channel_usable,
    blind_fleet,
    contributions_for,
    draw_balanced_slice,
    draw_latent_slice,
    eligible_pool,
    exact_wrong_majority,
    fleet_of,
    ladder,
    latent_blind_fleet,
    majority,
)
from pharos.governance.policy import (
    DEPLOYABLE,
    POLICIES,
    POLICY_SEED,
    UNIFORM_SEEDS,
    Policy,
    choose_anchors,
    policy_channel,
    policy_consensus,
    policy_deviation,
    policy_margin,
    policy_oracle,
    policy_posterior,
    policy_shortfall,
    select,
)
from pharos.governance.shape import (
    ALPHA,
    MIN_STRATUM,
    NULL_DRAWS,
    Dispersion,
    dispersion,
)
from pharos.governance.view import ServerObservation, fleet_view, observe, observed

__all__ = [
    "ALPHA",
    "BLIND",
    "BLIND_RUNGS",
    "CHANNEL_ENTANGLEMENT_SLACK",
    "DEPLOYABLE",
    "HALVED",
    "LATENT_ATTEMPTS",
    "LATENT_CARRIAGE_QUANTILE",
    "LATENT_NULL_DRAWS",
    "LATENT_SEED_STRIDE",
    "LATENT_SLICE",
    "MASK_SEED",
    "MIN_STRATUM",
    "NULL_DRAWS",
    "PERMUTATIONS",
    "PERMUTATION_SEED",
    "POLICIES",
    "POLICY_SEED",
    "REFUSED_EXIT",
    "REPAIRED",
    "REPORT_BUDGET",
    "RUNGS",
    "UNIFORM_SEEDS",
    "WRONG_THRESHOLD",
    "AbstentionCell",
    "AuditOutcome",
    "ChannelCarriage",
    "ChannelCheck",
    "ChannelUnusableError",
    "Detection",
    "Dispersion",
    "LatentSlice",
    "Policy",
    "Scored",
    "ServerObservation",
    "ThresholdSpread",
    "assert_channel_usable",
    "authority_ruling",
    "baseline_errors",
    "beats_every_draw",
    "blind_fleet",
    "choose_anchors",
    "compartment_carriage",
    "contributions_for",
    "detect",
    "dispersion",
    "draw_balanced_slice",
    "draw_latent_slice",
    "eligible_pool",
    "evaluate_audit",
    "exact_wrong_majority",
    "first_budget_halving",
    "fleet_of",
    "fleet_view",
    "ladder",
    "latent_blind_fleet",
    "majority",
    "observe",
    "observed",
    "policy_channel",
    "policy_consensus",
    "policy_deviation",
    "policy_margin",
    "policy_oracle",
    "policy_posterior",
    "policy_shortfall",
    "rates_from",
    "scan_channels",
    "score",
    "select",
    "stratified_delta",
    "summarize_thresholds",
    "threshold",
    "verdict_rates",
]
